service: authorization-service
frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

plugins: ["serverless-webpack", "serverless-dotenv-plugin"]

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:REGION}
  apiGateway:
    minimumCompressionSize: 1024

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
