service: import-service
frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

plugins: ["serverless-webpack", "serverless-dotenv-plugin"]

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:REGION}
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    SQS_ENDPOINT: https://sqs.${env:REGION}.amazonaws.com/${env:SQS_CODE}/${env:SQS_NAME}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::${env:BUCKET}"
            - "arn:aws:s3:::${env:BUCKET}/*"
        - Effect: "Allow"
          Action: "sqs:*"
          Resource:
            - "arn:aws:sqs:${env:REGION}:${env:SQS_CODE}:${env:SQS_NAME}"

functions:
  importProductsFile:
    handler: handler.importProductsByCsvFile
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer:
            arn: ${env:AUTH_ARN}
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
          querystrings:
            name: string
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET}
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:PREFIX}/
            - suffix: .csv
