service: import-service
frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

plugins: ["serverless-webpack", "serverless-dotenv-plugin"]

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:REGION}
  apiGateway:
    minimumCompressionSize: 1024
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::${env:BUCKET}"
            - "arn:aws:s3:::${env:BUCKET}/*"

functions:
  importProductsFile:
    handler: handler.importProductsByCsvFile
    events:
      - http:
          path: import
          method: get
          cors:
            origin: "*"
          querystrings:
            name: string
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET}
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:PREFIX}/
            - suffix: .csv
